development:
  clients:
    default:
      database: k8scollector
      hosts:
        <%= ENV.has_key?('K8SCOLLECTOR_MASTER_PORT_27017_TCP_ADDR') and ENV.has_key?('K8SCOLLECTOR_MASTER_PORT_27017_TCP_PORT') ? "- #{ENV['K8SCOLLECTOR_MASTER_PORT_27017_TCP_ADDR']}:#{ENV['K8SCOLLECTOR_MASTER_PORT_27017_TCP_PORT']}" : '- localhost:27017' %>
production:
  clients:
    default:
      database: k8scollector
      hosts:
        <%= ENV.has_key?('K8SCOLLECTOR_MASTER_PORT_27017_TCP_ADDR') and ENV.has_key?('K8SCOLLECTOR_MASTER_PORT_27017_TCP_PORT') ? "- #{ENV['K8SCOLLECTOR_MASTER_PORT_27017_TCP_ADDR']}:#{ENV['K8SCOLLECTOR_MASTER_PORT_27017_TCP_PORT']}" : '- localhost:27017' %>
