#!/bin/bash

# Please run this script from the root folder of the project

show_usage()
{
echo -e "\e[97m"
cat << EOF

Usage: k8scollectorctl COMMAND

A simple command line client for the 6fusion Kubernetes Collector

Options:

  -h    Print usage

Commands:

  install      Install the Kubernetes Collector
  upgrade      Upgrade the Kubernetes Collector
  uninstall    Uninstall the Kubernetes Collector

EOF
exit 0
}

show_invalid_command()
{
  echo -e "\e[97m"
  echo "k8scollectorctl: '$1' is not a valid command." >&2
  echo "See 'k8scollectorctl -h'." >&2
  echo
  exit 1
}

# Main start of the script

if [ "$1" == "" ]; then
  show_usage
fi

while getopts ":h" opt; do
  case $opt in
    h)
      show_usage
      ;;
    \?)
      show_invalid_option
      ;;
  esac
done
shift $(($OPTIND -1))

COMMAND=$1
shift 1

case $COMMAND in
  install)
    echo "Installing 6fusion Kubernetes Collector..."
    kubectl create -f ./kubernetes/k8scollector-namespace.yaml > /dev/null 2>&1
    kubectl create -f ./kubernetes/k8scollector.yaml
    echo -e "\e[97mInstalling 6fusion Kubernetes Collector...\e[92mOK"
    ;;
  upgrade)
    echo "Shutting down 6fusion Kubernetes Collector before upgrading..."
    kubectl delete pod 6fusion-k8scollector --namespace=6fusion-system
    kubectl delete secret on-premise-secret --namespace=6fusion-system
    kubectl delete secret kube-secret --namespace=6fusion-system
    kubectl delete serviceaccount 6fusion-k8scollector --namespace=6fusion-system
    echo "Upgrading 6fusion Kubernetes Collector. Please wait..."
    sleep 30
    kubectl create -f ./kubernetes/k8scollector-namespace.yaml > /dev/null 2>&1
    kubectl create -f ./kubernetes/k8scollector.yaml
    echo -e "\e[97mUpgrading 6fusion Kubernetes Collector...\e[92mOK"
    ;;
  uninstall)
    echo "Uninstalling 6fusion Kubernetes Collector..."
    kubectl delete pod 6fusion-k8scollector --namespace=6fusion-system
    kubectl delete secret on-premise-secret --namespace=6fusion-system
    kubectl delete secret kube-secret --namespace=6fusion-system
    kubectl delete serviceaccount 6fusion-k8scollector --namespace=6fusion-system
    echo -e "\e[97mUninstalling 6fusion Kubernetes Collector...\e[92mOK"
    ;;
  *)
    show_invalid_command $COMMAND
esac
