development:
  sessions:
    default:
      database: k8scollector
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: k8scollector
      hosts:
        - localhost:27017