apiVersion: v1
kind: ServiceAccount
metadata:
  name: 6fusion-k8scollector
  namespace: 6fusion-system
---
apiVersion: v1
kind: Secret
metadata:
  name: kube-secret
  namespace: 6fusion-system
data:
  kube-host: "MTAuMy4wLjEK"  # IP address or domain of the kubernetes API server
  kube-port: "NDQzCg=="              # Port of the kubernetes API server
  kube-token: ""                     # Token of the kubernetes API server (specify only for remote clusters)
  kube-use-ssl: "MQo="               # Use 1 for true and 0 for false
  kube-verify-ssl: "MAo="            # Use 1 for true and 0 for false
  cadvisor-host: "MTAuMC4wLjE4Ngo="
  cadvisor-port: "NDE5NAo="          # cAdvisor port (usually 4194)
---
apiVersion: v1
kind: Secret
metadata:
  name: on-premise-secret
  namespace: 6fusion-system
data:
  host: "YTA2ZDFiY2E2MjgyNDExZTZhNDRhMTI0ZDhlMmY0ZjgtNDQ4NTM0NDM5LnVzLWVhc3QtMS5lbGIuYW1hem9uYXdzLmNvbQo="  # IP address or domain of the 6fusion On Premise API server
  port: "ODAK"                  # Port of the 6fusion On Premise API server
  token: ""                     # Token to access the 6fusion On Premise API server
  use-ssl: "MAo="               # Use 1 for true and 0 for false
  verify-ssl: "MAo="            # Use 1 for true and 0 for false
  organization-id: "Nzc2MTYzLWI3NTkzNDRiN2FiYTQyMjQ5ZmQyZGQ0YWVjMDc1NTljCg=="  # Organization ID of the one already created in the 6fusion On Premise API server
---
apiVersion: v1
kind: Pod
metadata:
  name: 6fusion-k8scollector
  namespace: 6fusion-system
  labels:
    6fusion-app: k8scollector
spec:
  containers:
  - name: k8scollector
    image: 6fusion/kubernetes-collector:0.1.3  # Docker image of the 6fusion Kubernetes Collector
    volumeMounts:
    - name: kube-secret
      mountPath: /var/run/secrets/k8scollector/kube
    - name: on-premise-secret
      mountPath: /var/run/secrets/k8scollector/on-premise
  - name: k8scollector-mongodb
    image: mongo:3.2
    volumeMounts:
    - mountPath: /data/db
      name: "k8scollector-mongodb"
  volumes:
  - name: on-premise-secret
    secret:
      secretName: on-premise-secret
  - name: kube-secret
    secret:
      secretName: kube-secret
  - name: "k8scollector-mongodb"
    hostPath:
      path: "/var/lib/k8scollector/data/db"
